### ISSUE TITLE
给加密的信息生成签名 的时候为什么nonce为空 我是python2.7版本

### ISSUE THREAD

**Issue by gilbert-yuan** [zgs225/dingtalk_crypto#1]

**Comment by zgs225** [comment]
我先查查这个问题。这个库是错误的，请不要使用这个库。可以参考里面的部分实现。等这段时间我什么时候把这个库重写一下吧。

**Comment by gilbert-yuan** [comment]
错误的？解密是正确的，用这个库i自己加密自己解密，是没有问题 。
应该是少一个buf.seek(0) 。 这样能正常生成nonce 但是注册回调URL 还是不对 ， 还是返回字符不是success所以猜测是库的原因。您手头有在开发钉钉么，能指导下么。。

**Comment by gilbert-yuan** [comment]
def random_alpha(length=6):
    """
    随机生成指定长度的 Alpha 字符串
    :param length: int
    :return: str
    """
    with contextlib.closing(StringIO.StringIO()) as buf:
        for _ in xrange(length):
            buf.write(random.choice(alpha))
        **buf.seek(0)**
        return buf.read()

**Comment by zgs225** [comment]
我目前不在开发钉钉，钉钉开发的也少。这个是钉钉官网出的 Python SDK，你使用这个吧。[钉钉SDK](https://open-doc.dingtalk.com/doc.htm?spm=a219a.7386797.0.0.TzsyFZ#?docId=103132&docType=1)
