### ISSUE TITLE
字符集方面有严重的bug是指什么

### ISSUE THREAD

**Issue by Funnyang** [zgs225/dingtalk_crypto#2]
你好，请问您说的字符集严重 bug 是指什么？由于 Python 版本的原因，我是用 Python3.6 重写了，不知道是否存在同样问题，写 Python 时间不长，望指教！

**Comment by zgs225** [comment]
钉钉返回的数据都是 utf-8 的，但是 python2 的默认字符集不是 utf-8，所以在有中文的时候，Encode和Decode会出现错误。你可以试试。

**Comment by Funnyang** [comment]
好的，谢谢，我使用的是 Python 3.6，所有加解密都是基于 bytes 类型，编码解码也是 utf-8，应该没有问题，多谢指教。
